#!/bin/bash
set -e

ColorOFF='\033[0m'
BRed='\033[1;31m'
BGreen='\033[1;32m'

exit_code=0
while read -r fpath
do
    if ! grep 'declare(strict_types=1);' "$fpath" > /dev/null
    then
        echo -e "[strict_types:${BRed}NO${ColorOFF}] $fpath"
        exit_code=1
    fi
done < <(find "$@" -name '*.php' -not -path '*/vendor/*' | sort)

exit $exit_code